// Common
export type {
  UUID,
  ISODateString,
  JsonValue,
  JsonObject,
  ApiSuccess,
  ApiError,
  ApiResponse,
  Paginated,
} from './common/base';
export { meetsMinimumVersion } from './common/version';

// Models
export type { User, UserRole } from './models/user';
export type { Connection, ConnectionProvider, ConnectionStatus } from './models/connection';
export type {
  MessagingChannel,
  ChannelIdentity,
  ChannelLinkChallenge,
  BridgeWaState,
  BridgeDevice,
} from './models/channel';
export { BRIDGE_WA_STATES } from './models/channel';
export type {
  Suggestion,
  SuggestionKind,
  SuggestionStatus,
  SuggestionOption,
  SuggestionSourceRef,
  ProposedAction,
  ProposedActionType,
} from './models/suggestion';
export type {
  Organization,
  OrgKind,
  OrgStatus,
  OrgRole,
  OrgMember,
  OrgMembership,
  OrgInvite,
  OrgInviteStatus,
} from './models/organization';
export {
  ORG_KINDS,
  ORG_STATUSES,
  ORG_ROLES,
  ORG_INVITE_STATUSES,
  roleMeetsMinimum,
} from './models/organization';
export type {
  CommercePlatform,
  ChannelAccount,
  ChannelAccountStatus,
  CommerceContact,
  CommerceConversation,
  CommerceConversationSummary,
  CommerceMessage,
  CommerceMessageDirection,
  CommerceMessageStatus,
  ConsentPurpose,
  ConsentState,
  ConsentSource,
  ContactConsent,
  SuppressionReason,
  Suppression,
  MessagingPolicy,
  CommerceJob,
  CommerceJobKind,
  CommerceJobStatus,
  ContactAttributes,
  CommerceTag,
  SegmentMatchMode,
  SegmentRule,
  SegmentDefinition,
  CommerceSegment,
  AudienceBlockReason,
  AudienceMember,
  AudiencePreview,
  MessagePricingCategory,
  MessageCostAttribution,
  RateUnit,
  CommerceRateCard,
  CommerceMessageRate,
  MessageCostState,
  MessageCostUnratedReason,
  CommerceMoneySummary,
  SpendLedgerKind,
  CommerceSpendCap,
  CommerceSpendUsage,
  CommercePlan,
  CommercePlanVersion,
  CommerceBillingCollector,
  CommerceSubscriptionView,
  CommerceStore,
  StoreSubscriptionStatus,
  CommerceStoreSubscription,
  CommerceInvoiceStatus,
  CommerceInvoiceLineKind,
  CommerceInvoice,
  CommerceInvoiceLine,
  CommercePaymentProvider,
  CommercePaymentAttemptStatus,
  CommercePaymentAttempt,
  TemplateCategory,
  TemplateStatus,
  MessageTemplate,
  BroadcastStatus,
  CommerceBroadcast,
  BroadcastRecipientStatus,
  BroadcastRecipient,
  BroadcastCostForecast,
  CommerceCostSummary,
  ContactImportStatus,
  ContactImportSkipReason,
  ContactImport,
  ContactImportRow,
  OptinLinkStatus,
  OptinLink,
} from './models/commerce';
export {
  COMMERCE_PLATFORMS,
  OUTBOUND_CAPABLE_PLATFORMS,
  CHANNEL_ACCOUNT_STATUSES,
  COMMERCE_MESSAGE_DIRECTIONS,
  COMMERCE_MESSAGE_STATUSES,
  CONSENT_PURPOSES,
  CONSENT_STATES,
  CONSENT_SOURCES,
  SUPPRESSION_REASONS,
  COMMERCE_JOB_KINDS,
  COMMERCE_JOB_STATUSES,
  CONTACT_IMPORT_STATUSES,
  CONTACT_IMPORT_SKIP_REASONS,
  OPTIN_LINK_STATUSES,
  SEGMENT_MATCH_MODES,
  AUDIENCE_BLOCK_REASONS,
  MESSAGE_PRICING_CATEGORIES,
  RATE_UNITS,
  MESSAGE_COST_STATES,
  SPEND_LEDGER_KINDS,
  COMMERCE_INVOICE_STATUSES,
  COMMERCE_INVOICE_LINE_KINDS,
  COMMERCE_BILLING_COLLECTORS,
  COMMERCE_STORES,
  STORE_SUBSCRIPTION_STATUSES,
  isEntitled,
  COMMERCE_PAYMENT_PROVIDERS,
  COMMERCE_PAYMENT_ATTEMPT_STATUSES,
  TEMPLATE_CATEGORIES,
  TEMPLATE_STATUSES,
  BROADCAST_STATUSES,
  BROADCAST_RECIPIENT_STATUSES,
} from './models/commerce';
export type { Briefing, BriefingSection } from './models/briefing';
export type { UserPreferences } from './models/preferences';
export type { Rating, InsightFeedback } from './models/feedback';
export { RATINGS, RATING_REWARD, POSITIVE_RATINGS } from './models/feedback';
export type { AgentMemory, MemorySource } from './models/memory';
export type { RunnerDevice, RunnerSession } from './models/runner';
export type { Project, ProjectWorkspaceBinding } from './models/project';
export type {
  ProcessRule,
  ProcessDomain,
  ProcessDimension,
  ProcessTier,
  ProcessRuleStatus,
  ProcessRuleSource,
} from './models/processRule';
export { KIND_TO_PROCESS_DOMAIN } from './models/processRule';
export type {
  Contact,
  ContactStatus,
  ContactInvite,
  InviteStatus,
  PublicUser,
  ContactWithUser,
  ContactInviteWithUsers,
} from './models/contact';
export { CONTACT_STATUSES, INVITE_STATUSES } from './models/contact';
export type {
  Conversation,
  ConversationType,
  ParticipantRole,
  PresenceStatus,
  ConversationParticipant,
  ConversationSummary,
} from './models/conversation';
export { CONVERSATION_TYPES } from './models/conversation';
export type {
  Message,
  MessageType,
  MessageStatus,
  SenderKind,
  ReactionType,
  MessageReaction,
  MessagePreview,
  ReadReceipt,
  ProposedEmail,
  ProposedRunnerSession,
  ProposedCommerceReply,
  ProposedActionStatus,
} from './models/message';
export {
  MESSAGE_TYPES,
  MESSAGE_STATUSES,
  REACTION_TYPES,
  PROPOSED_ACTION_STATUSES,
} from './models/message';
export type {
  CallKind,
  CallStatus,
  CallEndReason,
  RtcSessionDescription,
  RtcIceCandidate,
  CallSession,
  CallParticipant,
} from './models/call';
export { CALL_KINDS } from './models/call';

// API contracts
export type {
  AuthTokens,
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  GetAuthStatusResponse,
} from './api/auth';
export type { ListActivityRequest, ListActivityResponse } from './api/activity';
export type {
  StartCalendarConnectionResponse,
  StartMoneyConnectionResponse,
  ExchangeMoneyPublicTokenRequest,
  ConnectionResponse,
  ListConnectionsResponse,
} from './api/connections';
export type {
  GenerateInsightRequest,
  GenerateInsightResponse,
  InsightEngagementResponse,
} from './api/insights';
export type { SubmitFeedbackRequest, SubmitFeedbackResponse } from './api/feedback';
export type { GetBriefingResponse } from './api/briefing';
export type {
  ListSuggestionsResponse,
  SnoozeSuggestionRequest,
  SnoozeSuggestionResponse,
  DismissSuggestionResponse,
  MarkSuggestionDoneResponse,
  RequestDraftRequest,
  RequestDraftResponse,
  ChatAboutSuggestionRequest,
  ChatAboutSuggestionResponse,
} from './api/suggestions';
export type {
  ListMemoriesRequest,
  ListMemoriesResponse,
  UpdateMemoryRequest,
  UpdateMemoryResponse,
  DeleteMemoryResponse,
} from './api/memory';
export type {
  ListProcessRulesRequest,
  ListProcessRulesResponse,
  CreateProcessRuleRequest,
  CreateProcessRuleResponse,
  UpdateProcessRuleRequest,
  UpdateProcessRuleResponse,
  DeleteProcessRuleResponse,
} from './api/processRules';
export {
  GMAIL_LOOKBACK_MIN_DAYS,
  GMAIL_LOOKBACK_MAX_DAYS,
  CALENDAR_LOOKAHEAD_MIN_DAYS,
  CALENDAR_LOOKAHEAD_MAX_DAYS,
} from './api/insights';
export type {
  VerifyEmailRequest,
  VerifyEmailResponse,
  ResendVerificationResponse,
} from './api/emailVerification';
export { EMAIL_VERIFICATION_CODE_LENGTH } from './api/emailVerification';
export type {
  RequestPasswordResetRequest,
  RequestPasswordResetResponse,
  ConfirmPasswordResetRequest,
  ConfirmPasswordResetResponse,
} from './api/passwordReset';
export {
  PASSWORD_RESET_CODE_LENGTH,
  PASSWORD_RESET_MIN_PASSWORD_LENGTH,
} from './api/passwordReset';
export type {
  GetPreferencesResponse,
  UpdatePreferencesRequest,
  UpdatePreferencesResponse,
} from './api/preferences';
export type {
  SearchUsersRequest,
  SearchUsersResponse,
  ListContactsResponse,
  SendInviteRequest,
  SendInviteResponse,
  ListInvitesResponse,
  RespondInviteRequest,
  RespondInviteResponse,
  BlockContactRequest,
  BlockContactResponse,
} from './api/contacts';
export type {
  CreateConversationRequest,
  CreateConversationResponse,
  ListConversationsResponse,
  GetConversationResponse,
  GetStewraConversationResponse,
  AddParticipantsRequest,
  AddParticipantsResponse,
  LeaveConversationResponse,
  MarkReadRequest,
  MarkReadResponse,
} from './api/conversations';
export type {
  SendMessageRequest,
  SendMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  GetMessageResponse,
  ReactRequest,
  ReactResponse,
  DeleteMessageResponse,
  SendVoiceMessageResponse,
  SendMediaMessageResponse,
  ListReadReceiptsResponse,
  ConfirmEmailAction,
  ConfirmEmailRequest,
  ConfirmEmailResponse,
  ConfirmRunnerSessionAction,
  ConfirmRunnerSessionRequest,
  ConfirmRunnerSessionResponse,
  ConfirmCommerceReplyAction,
  ConfirmCommerceReplyRequest,
  ConfirmCommerceReplyResponse,
} from './api/messages';
export type { UploadAvatarResponse } from './api/avatar';
export type {
  AccountDeletionBlocker,
  AccountDeletionPreview,
  AccountDeletionResult,
  AccountDeletionRevocation,
  DeleteAccountRequest,
  DeleteAccountResponse,
  GetAccountDeletionPreviewResponse,
} from './api/account';
export type {
  GrantWhatsappPersonalConsentRequest,
  GrantWhatsappPersonalConsentResponse,
  StartBridgePairingResponse,
  ClaimBridgeTokenRequest,
  ClaimBridgeTokenResponse,
  ListBridgeDevicesResponse,
  RevokeBridgeDeviceResponse,
  GetWhatsappPersonalResponse,
  GetEmailOverWhatsappResponse,
  SetEmailOverWhatsappRequest,
  SetEmailOverWhatsappResponse,
} from './api/channels';
export {
  WHATSAPP_PERSONAL_CONSENT_VERSION,
  WHATSAPP_PERSONAL_CONSENT_SENTENCE,
  normalizeConsentSentence,
  isConsentSentenceValid,
} from './api/channels';
export type {
  StartRunnerPairingResponse,
  ClaimRunnerTokenRequest,
  ClaimRunnerTokenResponse,
  ListRunnerDevicesResponse,
  RevokeRunnerDeviceResponse,
  GetRunnerStatusResponse,
  StartRunnerSessionRequest,
  StartRunnerSessionResponse,
  StartOrgRunnerSessionRequest,
  UpdateRunnerDeviceRequest,
  UpdateRunnerDeviceResponse,
  MoveRunnerDeviceRequest,
  MoveRunnerDeviceResponse,
  PromptRunnerSessionRequest,
  DecideRunnerPermissionRequest,
  RunnerSessionActionResponse,
  ListRunnerSessionsResponse,
  PushRunnerSessionResponse,
  OpenRunnerPrRequest,
  OpenRunnerPrResponse,
} from './api/runner';
export type { InboundSms, ListInboundSmsResponse } from './api/telnyx';
export type {
  CreateProjectRequest,
  CreateProjectResponse,
  UpdateProjectRequest,
  UpdateProjectResponse,
  ListProjectsResponse,
  GetProjectResponse,
  ArchiveProjectResponse,
  BindProjectWorkspaceRequest,
  BindProjectWorkspaceResponse,
  ListProjectWorkspacesResponse,
  UnbindProjectWorkspaceResponse,
  ListOrgProjectBindingsResponse,
} from './api/projects';
export type {
  GithubRepoInfo,
  GetGithubAppStatusResponse,
  LinkGithubInstallationRequest,
  LinkGithubInstallationResponse,
  UnlinkGithubInstallationResponse,
} from './api/githubApp';
export type {
  ProvisionHostedRunnerRequest,
  GetHostedRunnerResponse,
  HostedRunnerResponse,
  DestroyHostedRunnerResponse,
  UpdateHostedRunnerCredentialRequest,
  RunnerGitCredentialsResponse,
  HostedWorkspaceSpec,
  HostedWorkspacesResponse,
} from './api/hostedRunner';
export type {
  IceServerConfig,
  TurnCredentialsResponse,
  CallPushPlatform,
  RegisterCallPushTokenRequest,
  RegisterCallPushTokenResponse,
  ListCallHistoryResponse,
} from './api/calls';
export type {
  EmailApprovalPushData,
  SuggestionPushData,
  PushPlatform,
  RegisterAndroidPushTokenRequest,
  RegisterIosPushTokenRequest,
  RegisterPushTokenRequest,
  RegisterPushTokenResponse,
} from './api/push';
export {
  EMAIL_APPROVAL_ACTION_APPROVE,
  EMAIL_APPROVAL_ACTION_DENY,
  EMAIL_APPROVAL_ANDROID_CHANNEL_ID,
  EMAIL_APPROVAL_CATEGORY,
  EMAIL_APPROVAL_PUSH_BODY,
  EMAIL_APPROVAL_PUSH_TITLE,
  SUGGESTION_ANDROID_CHANNEL_ID,
  SUGGESTION_CATEGORY,
  SUGGESTION_PUSH_BODY,
  SUGGESTION_PUSH_TITLE,
} from './api/push';

export type {
  CreateOrgRequest,
  CreateOrgResponse,
  ConvertOrgRequest,
  ConvertOrgResponse,
  ListOrgsResponse,
  GetOrgResponse,
  SetActiveOrgRequest,
  SetActiveOrgResponse,
  ListOrgMembersResponse,
  CreateOrgInviteRequest,
  CreateOrgInviteResponse,
  AcceptOrgInviteRequest,
  AcceptOrgInviteResponse,
  DeleteOrgInviteResponse,
  UpdateOrgMemberRequest,
  UpdateOrgMemberResponse,
  DeleteOrgMemberResponse,
} from './api/organizations';
export type {
  EmbeddedSignupConfig,
  ListChannelAccountsResponse,
  CreateChannelAccountRequest,
  CreateChannelAccountResponse,
  DeleteChannelAccountResponse,
  ListCommerceConversationsRequest,
  ListCommerceConversationsResponse,
  ListCommerceMessagesRequest,
  ListCommerceMessagesResponse,
  CreateCommerceMessageRequest,
  CreateCommerceMessageResponse,
  SendConversationTemplateRequest,
  SendConversationTemplateResponse,
  ListContactConsentsResponse,
  RecordContactConsentRequest,
  RecordContactConsentResponse,
  ListSuppressionsRequest,
  ListSuppressionsResponse,
  CreateSuppressionRequest,
  CreateSuppressionResponse,
  DeleteSuppressionResponse,
  GetMessagingPolicyResponse,
  UpdateMessagingPolicyRequest,
  UpdateMessagingPolicyResponse,
  AttestMessagingPolicyRequest,
  AttestMessagingPolicyResponse,
  ListCommerceContactsRequest,
  ListCommerceContactsResponse,
  CommerceContactWithTags,
  CreateCommerceContactRequest,
  CreateCommerceContactResponse,
  CreateContactImportResponse,
  ListContactImportsResponse,
  GetContactImportResponse,
  CreateOptinLinkRequest,
  CreateOptinLinkResponse,
  ListOptinLinksResponse,
  DisableOptinLinkResponse,
  GetCommerceContactResponse,
  UpdateCommerceContactRequest,
  UpdateCommerceContactResponse,
  AddContactTagRequest,
  AddContactTagResponse,
  RemoveContactTagResponse,
  ListCommerceTagsResponse,
  DeleteCommerceTagResponse,
  ListCommerceSegmentsResponse,
  CreateCommerceSegmentRequest,
  CreateCommerceSegmentResponse,
  GetCommerceSegmentResponse,
  UpdateCommerceSegmentRequest,
  UpdateCommerceSegmentResponse,
  DeleteCommerceSegmentResponse,
  PreviewSegmentRequest,
  PreviewSegmentResponse,
  ListSegmentMembersRequest,
  ListSegmentMembersResponse,
  ListMessageTemplatesRequest,
  ListMessageTemplatesResponse,
  CreateMessageTemplateRequest,
  CreateMessageTemplateResponse,
  SyncMessageTemplatesRequest,
  SyncMessageTemplatesResponse,
  DeleteMessageTemplateResponse,
  ListBroadcastsResponse,
  CreateBroadcastRequest,
  CreateBroadcastResponse,
  GetBroadcastResponse,
  PreviewBroadcastRequest,
  PreviewBroadcastResponse,
  CancelBroadcastResponse,
  ResumeBroadcastResponse,
  ListBroadcastRecipientsRequest,
  ListBroadcastRecipientsResponse,
  GetCommerceCostsRequest,
  GetCommerceCostsResponse,
  ListCommerceJobsRequest,
  ListCommerceJobsResponse,
  LoadRateCardRequest,
  LoadRateCardRate,
  LoadRateCardResponse,
  ListRateCardsResponse,
  GetRateCardResponse,
  SetSpendCapRequest,
  SetSpendCapResponse,
  ListSpendCapsResponse,
  GetOrgSpendResponse,
  UpsertPlanRequest,
  UpsertPlanResponse,
  ListPlansResponse,
  SetSubscriptionRequest,
  SetSubscriptionResponse,
  GetOrgBillingResponse,
  CommercePaymentMethodState,
  StartPaymentMethodSetupResponse,
  ConfirmPaymentMethodRequest,
  ConfirmPaymentMethodResponse,
  ClaimStorePurchaseRequest,
  ClaimStorePurchaseResponse,
  CommerceDelinquency,
  CommerceDelinquencyState,
  ListInvoicesResponse,
  GetInvoiceResponse,
  MarkInvoicePaidRequest,
  MarkInvoicePaidResponse,
  ChargeInvoiceResponse,
} from './api/commerce';

// Realtime (Socket.IO) contract
export { CLIENT_EVENTS, SERVER_EVENTS } from './realtime/events';
export type { ClientEvent, ServerEvent } from './realtime/events';
export type {
  PresenceSubscribePayload,
  PresenceUpdateEvent,
  ContactInviteReceivedEvent,
  ContactInviteAcceptedEvent,
  ChatJoinPayload,
  ChatTypingPayload,
  ChatMarkReadPayload,
  ChatMessageEvent,
  ChatDeliveredEvent,
  ChatReadEvent,
  ChatTypingEvent,
  ChatReactionEvent,
  CallInitiatePayload,
  CallLifecyclePayload,
  CallSignalPayload,
  CallIcePayload,
  CallIncomingEvent,
  CallAnsweredEvent,
  CallDeclinedEvent,
  CallEndedEvent,
  CallRemoteOfferEvent,
  CallRemoteAnswerEvent,
  CallRemoteIceEvent,
  CallErrorEvent,
  StewraThinkingEvent,
  StewraReplyEvent,
  StewraReplyChunkEvent,
  StewraErrorEvent,
} from './realtime/payloads';

// Realtime — the /bridge namespace (Stewra Bridge on the user's own machine)
export { BRIDGE_CLIENT_EVENTS, BRIDGE_SERVER_EVENTS, BRIDGE_VOICE_MIN_VERSION } from './realtime/bridge';
export type {
  BridgeClientEvent,
  BridgeServerEvent,
  BridgeHelloPayload,
  BridgeStatePayload,
  BridgeInboundPayload,
  BridgeVoiceNote,
  BridgeAllowedChat,
  BridgeAllowedChatsPayload,
  BridgeSendPayload,
  BridgeSendAck,
} from './realtime/bridge';

// Realtime — the /runner namespace (Stewra Runner on the user's own machine: laptop or their cloud VM)
export {
  RUNNER_CLIENT_EVENTS,
  RUNNER_SERVER_EVENTS,
  RUNNER_HARNESS_IDS,
  CLAUDE_CODE_CREDENTIAL_FORMS,
  RUNNER_CREDENTIAL_FORMS,
  runnerCredentialProblem,
  RUNNER_DEVICE_KINDS,
  RUNNER_ENVIRONMENTS,
  RUNNER_CONTAINER_STATUSES,
  RUNNER_SESSION_STATUSES,
  RUNNER_UPDATE_KINDS,
  RUNNER_PERMISSION_KINDS,
  RUNNER_UI_EVENTS,
} from './realtime/runner';
export type {
  RunnerClientEvent,
  RunnerServerEvent,
  RunnerUiEvent,
  RunnerHarnessId,
  RunnerCredentialForm,
  RunnerDeviceKind,
  RunnerEnvironment,
  RunnerContainerStatus,
  RunnerSessionStatus,
  RunnerUpdateKind,
  RunnerPermissionKind,
  RunnerHarnessInfo,
  RunnerWorkspace,
  RunnerHelloPayload,
  RunnerStartSessionPayload,
  RunnerStartSessionAck,
  RunnerPromptPayload,
  RunnerCancelPayload,
  RunnerUpdateAvailablePayload,
  RunnerSessionUpdatePayload,
  RunnerSessionDonePayload,
  RunnerPushPayload,
  RunnerOpenPrPayload,
  RunnerGitActionAck,
  RunnerPermissionOption,
  RunnerPermissionPromptPayload,
  RunnerPermissionDecisionPayload,
} from './realtime/runner';

// Audit
export type { AuditResourceType, AuditAction, AuditEvent, NewAuditEvent } from './audit/events';

// Broker (the two-plane access contract)
export type {
  ResourceKind,
  BrokerRequest,
  BrokerResult,
  IBrokerClient,
  ModelMessage,
  ConversationTurn,
  IModelClient,
  AgentInsight,
} from './broker/contract';
